// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgqmpopmwzeoebhnjxjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZncW1wb3Btd3plb2ViaG5qeGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNTE4MDAsImV4cCI6MjA1MzYyNzgwMH0.gKhaCs1qp6orL7D7fqLOmf0jcHQPlUYGCbjuvIdJJdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);